### ISSUE TITLE
Mentions dropdown is limited to only ten.

### ISSUE THREAD

**Issue by Gadget-Guru** [friendica/red#806]
We need the ability to @mention more than only ten of our connections with the identical words in their profile name and/or domain.

e.g. There is a channel named LibertyPod and a domain of libertypod.com and I am unable to @mention LibertyPod because there are more than 10 channels in my connections that are located at libertypod.com.

**Comment by pafcu** [comment]
I don't think that increasing the number of the items in the dropdown is the correct answer: what happens when there are hundreds or thousands of people on the same domain? Probably the sorting of results need to be made smarter: i.e. first show channels where the first part matches, then the ones where only the domain matches. Would this help in your case?

**Comment by Gadget-Guru** [comment]
I agree that sorting the results as you describe would be the #1 solution. It would also be good to have a 'show more' at the bottom of the dropdown.

**Comment by pafcu** [comment]
I implemented sorting now. Maybe you could try the latest version from git? I didn't implement sorting for e.g. private messages yet, but when writing a post it should work.

**Comment by Gadget-Guru** [comment]
Working, thanks.

**Comment by Gadget-Guru** [comment]
I'm going to go ahead and leave this one open even though your sorting fix solves my issue and should solve practically anyone else's, because eventually, someone will need to 'show more' than ten. Thanks again @pafcu .

**Comment by pafcu** [comment]
I agree. Support for this almost exist currently. The SQL queries in mod/acl.php need to be modified to actually use the information passed along with the query. This is already done for groups, and should be fairly easy to add to the others by looking at how it's done for groups (there would be some trouble, because groups and people are retrieved separately). Getting it into the frontend Javascript might require some more work. Consider filing a request upstream at https://github.com/yuku-t/jquery-textcomplete.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#161
