### ISSUE TITLE
Don't make a new autocomplete query when it's not really needed

### ISSUE THREAD

**Issue by pafcu** [friendica/red#814]
When a user is typing a new query done for each letter that is written. However, often all the relevant results have already been sent to the user, and the result of the typing is just that some results are removed. This filtering could be done clinet-side, significantly reducing the number of queries needed.

**Comment by friendica** [comment]
..as long as the original results were complete. Often they are limited and the next search does pick up results which weren't available the first time due to query limits. We also had some discussion about this online recently and thought it might be advantageous to increase the limit as the search string gets longer to increase the likelihood that you have all available results. The first letter is going to pick up every channel with that letter in their name, hence the need to limit. It also may be useful to not search at all until 2 or possibly 3 chars have been entered. This was an option with the older autocompleter, but it may not have worked correctly.  As the string length increases, the returned results are increasingly relevant.

**Comment by redswede** [comment]
I noticed this behavior too. Only searching after letter number 2 seems like a good idea to me or we could put a timer counting to 3 before submitting the first query (3 sec after pressing the @). I think that such a timer is used in other places facebook being the only I know.

**Comment by pafcu** [comment]
This should actually be fixed now (results are cached when all results are known).

Number of letters that you have to type can be set by modifying the regular expressions given in view/js/autocomplete.js (this is already done for search_autocomplete) . Search for lines containing "match:" to find the correct spot. A timer can be added by passing the debounce option (in the same way as className and zIndex), see https://github.com/yuku-t/jquery-textcomplete/blob/master/doc/how_to_use.md

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#289
