### ISSUE TITLE
regression: network saved search can no longer search by connections

### ISSUE THREAD

**Issue by friendica** [friendica/red#830]
The saved search widget on the network page previously auto-completed connections and hashtags and the resulting search string in the case of connections was prefixed with '@' which triggers a connection search. The '@' is no longer added to the search so this result is no longer possible and it just performs a text search for the connection as opposed to an author search 

Additionally, adding extra chars does not seem to filter autocomplete results any further beyond the first available matches. For instance 'bob' will show bobo and bobbie but continuing to type 'bobb' still shows bobo in the results.

I know this is a very recent change and a lot of text inputs were modified to change the autocomplete behaviour, so just noting this as a regression so that it doesn't get lost.

**Comment by pafcu** [comment]
Thanks, hadn't noticed these. Lack of tags etc. is due to search being made to /acl instead of /search_ac. Filtering problem is due to a bug in caching when there are two autocompletes on the same page. The filtering probably works correctly if you have not previously typed anything into the nav search. I'll fix these later today.

A third regression is the lack of feedback while autocomplete is being populated. Previously a an indicator was shown next to the nav search (even if the actual searc box was somewhere else).

**Comment by friendica** [comment]
Should probably open another issue but somewhat related is a regression on the navbar people search. If I type @mike and hit return I expected to list all mikes in the directory, instead it completes the first mike in the autocomplete results and I only get that one. I don't see an easy way to "search entire directory for @mike" and neither myself nor Michael were in the initial results - so there's apparently no way to search for me. I tried cursor up on the first (selected) result to try and deselect it and got some weird modulus result instead. Don't know if this autocomplete widget lets you start off with nothing selected but I think that would be the preference/expectation (for me anyway).

**Comment by mike** [comment]
If you type @mike I expect to get an email notification from github :stuck_out_tongue_winking_eye:

**Comment by friendica** [comment]
At least that works... ;-)

**Comment by friendica** [comment]
much better - thanks.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#290
