### ISSUE TITLE
Use lang_selector() to build language selector in mod/admin.php

### ISSUE THREAD

**Issue by pafcu** [friendica/red#841]
To reduce duplicate code, ease maintenance, and get language names instead of just codes, mod/admin.php and view/tpl/admin_site.tpl should be modified to make use of the lang_selector() function found in include/text.php.

**Comment by friendica** [comment]
lang_selector() is primarily a developer option and used by a very small number of people who need the ability to toggle language dynamically. It over-rides the browser accept language. The browser's accept language is (and in my opinion should be) the preferred method of determining what language to display as it "generally" works for *everybody* (including visitors) without requiring any platform or server configuration.

That's the history here so that an informed decision can be made. We removed the language selector completely but found there were two developers (both translators) who required the functionality and added it back in as a module (and later an app).

**Comment by friendica** [comment]
Reviewing the code here and the admin (site) setting is used as a fallback if no suitable browser language is configured. So my last comment isn't valid and yes - this is a worthwhile change.

**Comment by pafcu** [comment]
In an ideal world the browser language should indeed be the thing that decides. However, it rarely works.

Despite English not being my native language, I use English as the primary language in my browser because:
1) Translations are usually terrible. I actually want to be able to use the sites, instead of having mistranslations and 50% of the interface in English anyway. This may not apply to Red, but browser settings usually apply to all web pages.
2) Most sites I visit have mostly english content. I don't want to have the interface in a different language than the content, because it always takes a while to "switch" language in my head. 

In most cases, asking for a site in my native language results in a worse experience for me.

However, sometimes the translations don't suck, and the content actually is in my desired language.

When I go to a hub where the content is mostly in English, I expect the interface to be in English. When I got to a hub where the content is mostly in in language X, I expect the interface to be in X (if such a translation exists). This seems to be the consensus among people I know. It's useful for a site owner to be able to specify which language to show to the user by default, no matter what the user's browser asks for.

As for lang_selector(), it should probably be modified so that it doesn't insert a new form element, so that it can be reused wherever a choice of language needs to be made.

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#170
