### ISSUE TITLE
Transparent navbar menu in mobile format

### ISSUE THREAD

**Issue by anaqreon** [friendica/red#891]
When logged out, the dropdown menu items are on top of a transparent background, making items difficult to see and tap. It seems to fix the problem to add a stylesheet item like this:
```
.navbar-collapse {
	background-color: #111111;
}
```
but I'm not sure where it is appropriate to put this in the CSS files, because I believe it derives from Bootstrap directly.

**Comment by git-marijus** [comment]
this usually happens with bootstrap if the panel is forced to have a specific height... did you see this on a "normal" login page or a home landing page?

**Comment by anaqreon** [comment]
I'm pretty sure it was only on the home landing page. Perhaps my workaround should be included in some form?

**Comment by friendica** [comment]
Oh but you're using your original landing page which messes with z-index if I recall.

**Comment by anaqreon** [comment]
To verify, I copied the /assets folder from commit https://github.com/friendica/red/commit/712bc643b5f26315602f34e9d9822ef83cb6b65a and I still get the behavior. Here is a screenshot: 

![screenshot](http://i.imgur.com/V1MK2Gg.png)

**Comment by friendica** [comment]
I can duplicate but I can't figure out what's causing it. 

util/config system projecthome 1

turns the project home page on

util/config system projecthome 0 

turns it off. 

When it's on and the small device navbar kicks in, it is indeed transparent. Turn off projecthome and it fixes itself. The background color seems to be set by navbar-inverse which is color 222 with a gradient applied. I can't see what's different in the css when the projecthome is swapped in and out, but the collapsed menu seems to lose inheritance to its background color. Note that assets/home.html does mess with z-index of the nav and header, which was done originally because there were some issues with the navbar display when the project homepage was first added. But I've tried commenting them out and see no change. At the moment I can't figure out what the culprit is.

**Comment by git-marijus** [comment]
I'll have a look at it today...

**Comment by git-marijus** [comment]
fixed in b31a2f109fc08d8440d3c9d8fabe221ee93527bb

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#305
