### ISSUE TITLE
Installation failure - database empty, memory spikes up to limit (tested up to 2G).

### ISSUE THREAD

**Issue by apooley** [friendica/red#930]
Perhaps this shouldn't be an issue, and apologies if I'm using the wrong system, but when installing Redmatrix I ran into this problem. The install/help says to import database.sql manually should this occur, but there is no database.sql file in the package. Attempted to import the mysql schema .sql file, but received errors. Running on a fresh Centos 6.5 install - thoughts?

**Comment by eminaksehirli** [comment]
I think I have a similar problem. In my case, it stops after the 3rd setup screen and there are segfaults in apache error log. I tried on Apache and nginx on Ubuntu 14.04, and apache on Centos, but I've never seen the 4th install screen. .htconfig.php file is created and it is filled with the correct information but I cannot find the "database.sql" file. I checked with gdb and the backtrace was starting with a function vspprintf and then continues with an zend optimization function. I tried to disable zend module and increasing the php script memory as suggested on the internet but the results was the same. Since the same problem happens on multiple platforms, I assume it's Red Matrix issue.

**Comment by eminaksehirli** [comment]
I could install when I checked out 2.2.1 tag.

**Comment by friendica** [comment]
Typo in the SQL file. Now fixed. Also updated the docs since database.sql no longer exists since we added postgres support, it's now install/schema_{dbtype}.sql

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#13

**Comment by jeroenpraat** [comment]
This issue was moved to redmatrix/redmatrix#185
